# https://github.com/dgtlmoon/changedetection.io/blob/master/docker-compose.yml

include:
  - ../compose-snippets/network-for-nginx-proxy.yaml

services:
  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io
    container_name: changedetection
    environment:
      PLAYWRIGHT_DRIVER_URL: ws://browser-sockpuppet-chrome:3000
      FETCH_WORKERS: 4
      TZ: Europe/Madrid
      BASE_URL: $BASE_URL
      USE_X_SETTINGS: 1
    # ports:
    #   - 127.0.0.1:5000:5000
    depends_on:
      browser-sockpuppet-chrome:
        condition: service_started
    hostname: changedetection
    restart: unless-stopped
    volumes:
      - ./datastore:/datastore
    extends:
      file: ../compose-snippets/logging-limits.yaml
      service: logging
    labels:
      - homepage.group=Apps
      - homepage.name=Changedetection
      - homepage.href=$BASE_URL
      - homepage.icon=changedetection
      - homepage.description=Detect website changes with alerts.
      - homepage.weight=10
      - homepage.widget.type=changedetectionio
      - homepage.widget.url=$BASE_URL
      - homepage.widget.key=$CHANGEDETECTION_API_KEY
      - diun.enable=true

  browser-sockpuppet-chrome:
    hostname: browser-sockpuppet-chrome
    image: dgtlmoon/sockpuppetbrowser:latest
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
    shm_size: 1.5g
    environment:
      SCREEN_WIDTH: 1920
      SCREEN_HEIGHT: 1024
      SCREEN_DEPTH: 16
      MAX_CONCURRENT_CHROME_PROCESSES: 10
      # CHROME_HEADFUL: true
    labels:
      - diun.enable=true
