include:
  - ../compose-snippets/network-for-nginx-proxy.yaml

services:
  hoarder:
    image: ghcr.io/hoarder-app/hoarder:${HOARDER_VERSION:-release}
    restart: unless-stopped
    volumes:
      - ./data:/data
    # ports:
    #   - 3000:3000
    env_file:
      - .env
    environment:
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      # OPENAI_API_KEY: ...
      DATA_DIR: /data
    extends:
      file: ../compose-snippets/logging-limits.yaml
      service: logging
    labels:
      - homepage.group=Apps
      - homepage.name=hoarder
      - homepage.href=//hoarder.home.lab
      - homepage.icon=sh-hoarder
      - homepage.description=Bookmark everything
      - homepage.weight=0

  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
    extends:
      file: ../compose-snippets/logging-limits.yaml
      service: logging

  meilisearch:
    image: getmeili/meilisearch:v1.11.1
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - ./meili_data:/meili_data
    extends:
      file: ../compose-snippets/logging-limits.yaml
      service: logging
