services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ./config:/config
      - type: volume
        source: usbdisk-on-raspberry-pi
        target: /data
        volume:
          nocopy: true
    # ports:
    #   - 8989:8989
    extends:
      file: ../compose-snippets/logging-limits.yaml
      service: logging
    labels:
      - homepage.group=*Arr
      - homepage.name=sonarr
      - homepage.href=//sonarr.home.lab
      - homepage.icon=sh-sonarr
      - homepage.description=TV organizer/manager
      - homepage.weight=20
      - homepage.widget.type=sonarr
      - homepage.widget.url=http://sonarr.home.lab
      - homepage.widget.key=$KEY_FOR_WIDGET
      - homepage.widget.enableQueue=true
      - diun.enable=true

include:
  - ../compose-snippets/volume-usbdisk-on-raspberry-pi.yaml
  - ../compose-snippets/network-for-nginx-proxy.yaml
