services:
  windmill_server:
    container_name: windmill_server
    image: ${WM_IMAGE}
    # pull_policy: always
    restart: unless-stopped
    # expose:
    #   - 8000
    #   - 2525
    environment:
      DATABASE_URL:
      MODE: server
    volumes:
      - ./logs:/tmp/windmill/logs
    networks:
      - default
      - network-postgres
    extends:
      file: ../compose-snippets/logging-limits.yaml
      service: logging

    labels:
      - homepage.group=Apps
      - homepage.name=Windmill
      - homepage.href=//windmill.home.lab
      - homepage.icon=sh-windmill
      - homepage.description=developer platform and workflow engine
      - homepage.weight=10

  windmill_worker:
    image: ${WM_IMAGE}
    container_name: windmill_worker_1
    # pull_policy: always
    environment:
      DATABASE_URL:
      MODE: worker
      WORKER_GROUP: default
    # to mount the worker folder to debug, KEEP_JOB_DIR=true and mount /tmp/windmill
    volumes:
      # mount the docker socket to allow to run docker containers from within the workers
      - /var/run/docker.sock:/var/run/docker.sock
      - ./logs:/tmp/windmill/logs
      - ./data/windmill/worker/cache:/tmp/windmill/cache
    networks:
      - default
      - network-postgres
    extends:
      file: ../compose-snippets/logging-limits.yaml
      service: logging

  windmill_worker_native:
    image: ${WM_IMAGE}
    pull_policy: always
    container_name: windmill_worker_native_1
    environment:
      DATABASE_URL:
      NUM_WORKERS: 2
      SLEEP_QUEUE: 200
      MODE: worker
      WORKER_GROUP: native
    volumes:
      - ./logs:/tmp/windmill/logs
    networks:
      - default
      - network-postgres
    extends:
      file: ../compose-snippets/logging-limits.yaml
      service: logging

  windmill_lsp:
    image: ghcr.io/windmill-labs/windmill-lsp:latest
    container_name: windmill_lsp
    pull_policy: always
    # expose:
    #   - 3001
    volumes:
      - ./lsp_cache:/root/.cache
    networks:
      - default
      - network-postgres
    extends:
      file: ../compose-snippets/logging-limits.yaml
      service: logging

include:
  - ../compose-snippets/network-postgres.yaml
  - ../compose-snippets/network-for-nginx-proxy.yaml
