# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/settings-schema.json

resource_providers:
  - name: trash_guides
    type: trash-guides
    clone_url: https://github.com/grota/trash-guides.git
    reference: master
    replace_default: true

  - name: config_templates
    type: config-templates
    clone_url: https://github.com/recyclarr/config-templates.git
    reference: master
    replace_default: true
