services:
  wg-easy:
    environment:
      # The server's hostname (clients will connect to):
      WG_HOST:

      # The Web UI Password:
      PASSWORD_HASH: $$2a$$12$$DS4l/vvpOH2CkS4GeUGRruGM6fcbvYvBBPx2P7ncqS.HvqKrPFPfm

      # 💡 This is the Pi-Hole Container's IP Address
      WG_DEFAULT_DNS:
      WG_DEFAULT_ADDRESS: 10.8.0.x
      WG_DEVICE: eth0
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    volumes:
      - ./etc_wireguard:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    extends:
      file: ../compose-snippets/logging-limits.yaml
      service: logging

    labels:
      - homepage.group=Apps
      - homepage.name=wg-easy
      - homepage.href=//vpn.home.lab
      - homepage.icon=sh-wireguard
      - homepage.description=Wireguard
      - homepage.weight=20
      - diun.enable=true
