services:
  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: mele@home.lab
      PGADMIN_DEFAULT_PASSWORD:
      PGADMIN_DISABLE_POSTFIX: 1
    # ports:
    #   - 8080:80
    volumes:
      - ${PWD}/servers.json:/pgadmin4/servers.json
      # needs on host: sudo chown 5050 data/pgadmin/pgadmin4.db
      # needs on host: sudo chmod  600 data/pgadmin/pgadmin4.db
      - ${PWD}/pgadmin4.db:/var/lib/pgadmin/pgadmin4.db
    extends:
      file: ../compose-snippets/logging-limits.yaml
      service: logging
    networks:
      - default
      - network-postgres

include:
  - ../compose-snippets/network-for-nginx-proxy.yaml
  - ../compose-snippets/network-postgres.yaml
