include:
  - ../compose-snippets/network-for-nginx-proxy.yaml

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage

    # ports:
    #   - 3000:3000
    environment:
      HOMEPAGE_ALLOWED_HOSTS: home.lab

    volumes:
      - ./config:/app/config
      - ./assets:/app/public/custom_assets
      - /var/run/docker.sock:/var/run/docker.sock

    labels:
      - diun.enable=true

    restart: unless-stopped
    extends:
      file: ../compose-snippets/logging-limits.yaml
      service: logging
