services:
  diun:
    image: crazymax/diun:latest
    container_name: diun
    command: serve
    volumes:
      - "./data:/data"
      - "./diun.yml:/diun.yml:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    hostname: diun
    environment:
      - TZ=Europe/Madrid
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
      - "DIUN_WATCH_WORKERS=2"
      - "DIUN_WATCH_SCHEDULE=0 */24 * * *"
      - "DIUN_WATCH_JITTER=30s"
      - "DIUN_PROVIDERS_DOCKER=true"
      - DIUN_NOTIF_TELEGRAM_TOKEN=$DIUN_NOTIF_TELEGRAM_TOKEN
      - DIUN_NOTIF_TELEGRAM_CHATIDS=$DIUN_NOTIF_TELEGRAM_CHATIDS
      # - DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true
      - 'DIUN_NOTIF_TELEGRAM_TEMPLATEBODY={{ if (eq .Entry.Status "new") }}New{{ else }}Updated{{ end }} tag for {{ if .Entry.Image.HubLink }}[{{ .Entry.Image.Path }}]({{ .Entry.Image.HubLink }}){{ else }}{{ .Entry.Image.Tag }}{{ end }}.'
      - DIUN_NOTIF_WEBHOOK_HEADERS_AUTHORIZATION=$DIUN_DASH_AUTH

    labels:
      - diun.enable=true

    restart: unless-stopped
    extends:
      file: ../compose-snippets/logging-limits.yaml
      service: logging
