services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - AUTO_UPDATE=true
      - RUN_OPTS=
    volumes:
      - ./config:/config
      - type: volume
        source: usbdisk-on-raspberry-pi
        target: /monitored
        volume:
          nocopy: true
          subpath: downloaded/monitored
    # ports:
    #   - 9117:9117
    extends:
      file: ../compose-snippets/logging-limits.yaml
      service: logging
    labels:
      - homepage.group=*Arr
      - homepage.name=Jackett
      - homepage.href=//jackett.home.lab
      - homepage.icon=sh-jackett
      - homepage.description=bittorrent api proxy
      - homepage.weight=90
      - homepage.widget.type=jackett
      - homepage.widget.url=http://jackett.home.lab

include:
  - ../compose-snippets/volume-usbdisk-on-raspberry-pi.yaml
  - ../compose-snippets/network-for-nginx-proxy.yaml
