services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8883:8080
    environment:
      - DOZZLE_HOSTNAME='mele-4c'
      - DOZZLE_NO_ANALYTICS=true
