services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # ports:
    #   - 8883:8080
    environment:
      - DOZZLE_HOSTNAME='mele-4c'
      - DOZZLE_NO_ANALYTICS=true
    extends:
      file: ../compose-snippets/logging-limits.yaml
      service: logging
    labels:
      - homepage.group=System
      - homepage.name=Dozzle
      - homepage.href=//dozzle.home.lab
      - homepage.icon=sh-dozzle
      - homepage.description=Real-time logging and monitoring for Docker
      - homepage.weight=25

include:
  - ../compose-snippets/network-for-nginx-proxy.yaml
