services:
  kopia:
    image: kopia/kopia:latest
    hostname: kopiahostname
    container_name: kopia
    restart: unless-stopped
    # ports:
    #     - 51515:51515
    # Setup the server that provides the web gui
    command:
      - server
      - start
      - --disable-csrf-token-checks
      - --insecure
      - --address=0.0.0.0:51515
      - --server-username=USERNAME
      - --server-password=SECRET_PASSWORD
    environment:
      # Set repository password
      KOPIA_PASSWORD: "testpw"
    volumes:
      # Mount local folders needed by kopia
      - $PWD/config:/app/config
      - $PWD/cache/app/cache
      - $PWD/logs:/app/logs
      # Mount local folders to snapshot
      - /home/grota/selfhost/:/data:ro
      # Mount repository location
      - $HOME/kopia-repo:/repository
      - $HOME/kopia-repo2:/repo2
      # Mount path for browsing mounted snaphots
      - /tmp/kopia-tmp/:/tmp:shared
    extends:
      file: ../compose-snippets/logging-limits.yaml
      service: logging

include:
  - ../compose-snippets/network-for-nginx-proxy.yaml
