services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ./config:/config
      - type: volume
        source: usbdisk-on-raspberry-pi
        target: /data
        volume:
          nocopy: true
    # ports:
    #   - 6767:6767
    extends:
      file: ../compose-snippets/logging-limits.yaml
      service: logging
    labels:
      - homepage.group=*Arr
      - homepage.name=bazarr
      - homepage.href=//bazarr.home.lab
      - homepage.icon=sh-bazarr
      - homepage.description=Subtitles
      - homepage.weight=60
      - homepage.widget.type=bazarr
      - homepage.widget.url=http://bazarr.home.lab
      - homepage.widget.key=$KEY_FOR_WIDGET

include:
  - ../compose-snippets/volume-usbdisk-on-raspberry-pi.yaml
  - ../compose-snippets/network-for-nginx-proxy.yaml
