include:
  - ../compose-snippets/network-for-nginx-proxy.yaml

services:
  beszel:
    image: 'henrygd/beszel'
    container_name: 'beszel'
    restart: unless-stopped
    # ports:
    #   - '8090:8090'
    volumes:
      - ./beszel_data:/beszel_data
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    extends:
      file: ../compose-snippets/logging-limits.yaml
      service: logging
    labels:
      - homepage.group=System
      - homepage.name=Beszel
      - homepage.href=//beszel.home.lab
      - homepage.icon=sh-beszel-light
      - homepage.description=server monitor with historical data
      - homepage.weight=20
      - homepage.widget.type=beszel
      - homepage.widget.url=http://beszel.home.lab
      - homepage.widget.username=$USERNAME_FOR_WIDGET
      - homepage.widget.password=$PASSWORD_FOR_WIDGET
      - homepage.widget.systemId=kx16aow6okh3by2

  beszel-agent:
    image: "henrygd/beszel-agent"
    container_name: "beszel-agent"
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # monitor other disks / partitions by mounting a folder in /extra-filesystems
      # - /mnt/disk/.beszel:/extra-filesystems/sda1:ro
    environment:
      PORT: 45876
      KEY: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMW3bWq06dvHpEYptDnT+gT67MgZPWc07PB/NhCA0S6u"
    extends:
      file: ../compose-snippets/logging-limits.yaml
      service: logging
