services:
  gluetun:
    image: qmcgaw/gluetun:v3
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun

    ports:
      - 8000:8000     # gluetun's control server port, exposed for the homepage gluetun widget.
      - 8888:8888/tcp # HTTP proxy, used by prowlarr
    #   - 8388:8388/tcp # Shadowsocks, gluetun's default is disabled
    #   - 8388:8388/udp # Shadowsocks, gluetun's default is disabled
    #
      - 8080:8080     # qbittorrent web ui port
    #   - 6881:6881     # qbittorrent tcp and udp connection ports https://hub.docker.com/r/linuxserver/qbittorrent
    #   - 6881:6881/udp # qbittorrent tcp and udp connection ports https://hub.docker.com/r/linuxserver/qbittorrent
      # - 9696:9696     # prowlarr web ui port
      - 8191:8191     # flaresolverr

    volumes:
      - ./config:/gluetun

    environment:
      # See https://github.com/qdm12/gluetun-wiki/tree/main/setup#setup
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=OFQBBTi5B0l+PXbKZeWyIalo/IBj5BM+KEaO3d1YVXg=
      - SERVER_COUNTRIES=United States
      - TZ=Europe/Rome
      - HTTPPROXY=on
      # - HTTPPROXY_LOG=on
      - UPDATER_PERIOD=72h
      # Workaround for qbittorent + gluetun "stalled" issue,
      # see https://github.com/qdm12/gluetun/issues/1407 https://github.com/qdm12/gluetun/issues/1277
      - HEALTH_VPN_DURATION_INITIAL=120s

    labels:
      - homepage.group=System
      - homepage.name=Gluetun
      - homepage.icon=sh-nordvpn
      - homepage.description=docker vpn toolkit
      - homepage.weight=20
      - homepage.widget.type=gluetun
      - homepage.widget.url=http://gluetun-control-server.home.lab
      - diun.enable=true

    extends:
      file: ../compose-snippets/logging-limits.yaml
      service: logging

    restart: unless-stopped
    container_name: gluetun
