services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    restart: unless-stopped
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/Madrid
    extends:
      file: ../compose-snippets/logging-limits.yaml
      service: logging

    # ports:
    #   - "${PORT:-8191}:8191"
    network_mode: "container:gluetun" # needs this because prowlarr needs to reach flaresolverr (and with this it will do so via localhost:8191).
