services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    restart: unless-stopped
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/Madrid
    extends:
      file: ../compose-snippets/logging-limits.yaml
      service: logging
    labels:
      - diun.enable=true
    # volumes:
    #   - ./flaresolverr_service.py:/app/flaresolverr_service.py

    # ports:
    #   - "${PORT:-8191}:8191"

    network_mode: "container:gluetun"
# include:
#   - ../compose-snippets/network-for-nginx-proxy.yaml
