include:
  - ../compose-snippets/network-for-nginx-proxy.yaml

services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    # extra_hosts:
    #   - 'host.docker.internal:host-gateway'
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    extends:
      file: ../compose-snippets/logging-limits.yaml
      service: logging
