include:
  - ../compose-snippets/network-for-nginx-proxy.yaml

services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    container_name: nginx-proxy-manager
    # extra_hosts:
    #   - 'host.docker.internal:host-gateway'
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    extends:
      file: ../compose-snippets/logging-limits.yaml
      service: logging
    labels:
      - homepage.group=System
      - homepage.name=Nginx Proxy Manager
      - homepage.href=//reverse-proxy.home.lab
      - homepage.icon=sh-nginx-proxy-manager
      - homepage.weight=10
      - homepage.widget.type=npm
      - homepage.widget.url=http://reverse-proxy.home.lab
      - homepage.widget.username=$USERNAME_FOR_WIDGET
      - homepage.widget.password=$PASSWORD_FOR_WIDGET
      - diun.enable=true
