services:
  tandoor:
    container_name: tandoor
    restart: unless-stopped
    image: vabene1111/recipes
    env_file:
      - ./.env
    volumes:
      - ./staticfiles:/opt/recipes/staticfiles
      - ./mediafiles:/opt/recipes/mediafiles
    networks:
      - default
      - network-postgres
    deploy:
      resources:
        limits:
          memory: 1000M
    extends:
      file: ../compose-snippets/logging-limits.yaml
      service: logging
    labels:
      - homepage.group=Apps
      - homepage.name=Tandoor
      - homepage.href=//tandoor.home.lab
      - homepage.icon=tandoor-recipes
      - homepage.description=Recipes (tandoor)
      - homepage.weight=25
      - diun.enable=true

include:
  - ../compose-snippets/network-postgres.yaml
  - ../compose-snippets/network-for-nginx-proxy.yaml
