include:
  - ../compose-snippets/network-for-nginx-proxy.yaml

services:
  dockge:
    image: louislam/dockge:1
    restart: unless-stopped
    container_name: dockge
    # ports:
    #   - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      # Stacks Directory
      # ⚠️ READ IT CAREFULLY. If you did it wrong, your data could end up writing into a WRONG PATH.
      # ⚠️ 1. FULL path only. No relative path (MUST)
      # ⚠️ 2. Left Stacks Path === Right Stacks Path (MUST)
      - /home/grota/selfhost:/home/grota/selfhost
    environment:
      - DOCKGE_STACKS_DIR=/home/grota/selfhost
    extends:
      file: ../compose-snippets/logging-limits.yaml
      service: logging

    labels:
      - homepage.group=System
      - homepage.name=Dockge
      - homepage.href=//dockge.home.lab
      - homepage.icon=sh-dockge
      - homepage.description=docker compose manager
      - homepage.weight=0
      - diun.enable=true
